import { Vehicle } from './types'
import { EUR_TO_FCFA } from './constants'

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: '1',
    brand: 'BYD',
    model: 'Seal EV',
    year: 2025,
    price_eur: 18500,
    price_fcfa: 18500 * EUR_TO_FCFA,
    mileage: 0,
    fuel_type: 'Électrique',
    transmission: 'Automatique',
    power: '313ch',
    color: 'Blanc',
    seats: 5,
    doors: 4,
    body_type: 'Berline',
    condition: 'neuf',
    description: 'La BYD Seal est une berline électrique premium avec une autonomie de 570km. Design sportif, intérieur luxueux avec écran rotatif 15.6 pouces. Technologie Blade Battery pour une sécurité maximale.',
    images: ['/placeholder-car.jpg'],
    status: 'disponible',
    views_count: 234,
    featured: true,
    verified: true,
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-03-15T10:00:00Z',
  },
  {
    id: '2',
    brand: 'Chery',
    model: 'Tiggo 8 Pro',
    year: 2025,
    price_eur: 14200,
    price_fcfa: 14200 * EUR_TO_FCFA,
    mileage: 0,
    fuel_type: 'Essence',
    transmission: 'Automatique',
    power: '197ch',
    color: 'Noir',
    seats: 7,
    doors: 5,
    body_type: 'SUV',
    condition: 'neuf',
    description: 'Le Chery Tiggo 8 Pro est un SUV 7 places spacieux et bien équipé. Moteur turbo 1.6L, écran tactile 12.3 pouces, caméra 360°, toit ouvrant panoramique.',
    images: ['/placeholder-car.jpg'],
    status: 'disponible',
    views_count: 187,
    featured: true,
    verified: true,
    created_at: '2026-03-14T10:00:00Z',
    updated_at: '2026-03-14T10:00:00Z',
  },
  {
    id: '3',
    brand: 'Geely',
    model: 'Coolray',
    year: 2024,
    price_eur: 9800,
    price_fcfa: 9800 * EUR_TO_FCFA,
    mileage: 12000,
    fuel_type: 'Essence',
    transmission: 'Automatique',
    power: '177ch',
    color: 'Rouge',
    seats: 5,
    doors: 5,
    body_type: 'SUV',
    condition: 'occasion',
    description: 'Le Geely Coolray est un SUV compact au design moderne. Turbo 1.5L, boîte DCT 7 rapports, écran tactile 10.25 pouces, conduite assistée niveau 2.',
    images: ['/placeholder-car.jpg'],
    status: 'disponible',
    views_count: 156,
    featured: true,
    verified: true,
    created_at: '2026-03-13T10:00:00Z',
    updated_at: '2026-03-13T10:00:00Z',
  },
  {
    id: '4',
    brand: 'Haval',
    model: 'Jolion',
    year: 2025,
    price_eur: 11500,
    price_fcfa: 11500 * EUR_TO_FCFA,
    mileage: 0,
    fuel_type: 'Hybride',
    transmission: 'Automatique',
    power: '190ch',
    color: 'Gris',
    seats: 5,
    doors: 5,
    body_type: 'SUV',
    condition: 'neuf',
    description: 'Le Haval Jolion Hybride combine efficacité et puissance. Motorisation hybride, consommation réduite, technologie embarquée complète avec écran 12.3 pouces.',
    images: ['/placeholder-car.jpg'],
    status: 'disponible',
    views_count: 142,
    featured: true,
    verified: true,
    created_at: '2026-03-12T10:00:00Z',
    updated_at: '2026-03-12T10:00:00Z',
  },
  {
    id: '5',
    brand: 'MG',
    model: 'ZS EV',
    year: 2025,
    price_eur: 13200,
    price_fcfa: 13200 * EUR_TO_FCFA,
    mileage: 0,
    fuel_type: 'Électrique',
    transmission: 'Automatique',
    power: '177ch',
    color: 'Bleu',
    seats: 5,
    doors: 5,
    body_type: 'SUV',
    condition: 'neuf',
    description: 'Le MG ZS EV est un SUV 100% électrique accessible. Autonomie 440km, charge rapide, intérieur spacieux et bien fini.',
    images: ['/placeholder-car.jpg'],
    status: 'disponible',
    views_count: 98,
    featured: false,
    verified: true,
    created_at: '2026-03-11T10:00:00Z',
    updated_at: '2026-03-11T10:00:00Z',
  },
  {
    id: '6',
    brand: 'BYD',
    model: 'Atto 3',
    year: 2024,
    price_eur: 15800,
    price_fcfa: 15800 * EUR_TO_FCFA,
    mileage: 5000,
    fuel_type: 'Électrique',
    transmission: 'Automatique',
    power: '204ch',
    color: 'Vert',
    seats: 5,
    doors: 5,
    body_type: 'SUV',
    condition: 'occasion',
    description: 'Le BYD Atto 3 est un SUV électrique au design unique. Autonomie 420km, intérieur design avec éléments sportifs, Blade Battery.',
    images: ['/placeholder-car.jpg'],
    status: 'vendu',
    views_count: 312,
    featured: false,
    verified: true,
    created_at: '2026-03-10T10:00:00Z',
    updated_at: '2026-03-10T10:00:00Z',
  },
  {
    id: '7',
    brand: 'Changan',
    model: 'UNI-T',
    year: 2025,
    price_eur: 12400,
    price_fcfa: 12400 * EUR_TO_FCFA,
    mileage: 0,
    fuel_type: 'Essence',
    transmission: 'Automatique',
    power: '188ch',
    color: 'Blanc',
    seats: 5,
    doors: 5,
    body_type: 'SUV',
    condition: 'neuf',
    description: 'Le Changan UNI-T est un SUV au design futuriste. Moteur Blue Whale 1.5T, conduite semi-autonome, écran tactile flottant.',
    images: ['/placeholder-car.jpg'],
    status: 'disponible',
    views_count: 76,
    featured: false,
    verified: true,
    created_at: '2026-03-09T10:00:00Z',
    updated_at: '2026-03-09T10:00:00Z',
  },
  {
    id: '8',
    brand: 'Great Wall',
    model: 'Poer',
    year: 2025,
    price_eur: 16800,
    price_fcfa: 16800 * EUR_TO_FCFA,
    mileage: 0,
    fuel_type: 'Diesel',
    transmission: 'Automatique',
    power: '163ch',
    color: 'Noir',
    seats: 5,
    doors: 4,
    body_type: 'Pick-up',
    condition: 'neuf',
    description: 'Le Great Wall Poer est un pick-up robuste et moderne. Moteur diesel 2.0T, 4x4 permanent, benne spacieuse, équipement premium.',
    images: ['/placeholder-car.jpg'],
    status: 'disponible',
    views_count: 203,
    featured: false,
    verified: true,
    created_at: '2026-03-08T10:00:00Z',
    updated_at: '2026-03-08T10:00:00Z',
  },
]
